https://github.com/Nandanks03/PES1UG21CS360_Jenkins/tree/main/PES1UG21CS360_Jenkins-main
pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[url: 'https://github.com/Nandanks03/PES1UG21CS360_Jenkins/tree/main/PES1UG21CS360_Jenkins-main']]])
            }
        }
        stage('Build') {
            steps {
                echo 'Building...'
                // Add your build steps here
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                // Add your test steps here
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                // Add your deploy steps here
            }
        }
    }
}
